import '@styles/global.css';

import { Raleway } from 'next/font/google';

import { Providers } from './provider';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Next14 TypeScript Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={raleway.className} style={{ height: '100vh', width: '100vw', overflow: 'hidden' }}>
        <Providers>
          {children}
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
