import '@styles/global.css';

import { Raleway } from 'next/font/google';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Next14 TypeScript Template',
  description: 'Generated by create next app',
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={raleway.className}>
        <div className="flex h-screen w-screen items-center justify-center">{children}</div>
      </body>
    </html>
  );
}
